/**
 * Represents the user student profile projects list.
 * Generated by JSONinja extension
 */

export interface StudentProjectListResponseItem {
    absenceRatio: number;
    absentCount: number;
    absentDurationMinutes: number;
    endDate: string;
    groupName: string;
    hasExceededAbsenceThreshold: boolean;
    justifiedCount: number;
    justifiedDurationMinutes: number;
    login: string;
    presentCount: number;
    presentDurationMinutes: number;
    projectInstanceId: number;
    projectName: string;
    registrationId: number;
    startDate: string;
    tooManyAbsences: boolean;
    tooManyAbsencesManualOverride: any | null;
    tooManyAbsencesManualOverrideComment: string;
    totalTrackedDurationMinutes: number;
    trackedEventsCount: number;
}

export type StudentProjectListResponse = StudentProjectListResponseItem[];
