/**
 * Represents the user student profile exams results
 * Generated by JSONinja extension
 */

export interface StudentExamListResponseExamItemResultItem {
    date: string;
    isSelfAssessment: boolean;
    requiredScore: number;
    scholarYear: number;
    score: number;
}

export interface StudentExamListResponseExamItemRequiredScoreItem {
    score: number;
    tekYear: number;
}

export interface StudentExamListResponseExamItemBest {
    date: string;
    scholarYear: number;
    score: number;
    title: string;
}

export interface StudentExamListResponseExamItem {
    best: StudentExamListResponseExamItemBest;
    examLineageKey: string;
    label: string;
    maxMark: number;
    requiredScore: number;
    requiredScores: StudentExamListResponseExamItemRequiredScoreItem[];
    results: StudentExamListResponseExamItemResultItem[];
    type: string;
}

export interface StudentExamListResponse {
    exams: StudentExamListResponseExamItem[];
}
